# fly.toml app configuration file generated for throbbing-sunset-5380 on 2023-06-13T22:32:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "throbbing-sunset-5380"
primary_region = "scl"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  JWT_SECRET = "asasf423r353tg343f42qef"
  PORT = "8080"
  STAGE = "prod"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
